#!/bin/bash
readonly DEFAULT_UID='1000'

#######################################
# Creates a new user and sets up default groups, UID, and password.
# Arguments:
#   1 - username: The name for the new user to be created
# Returns:
#   1 - If there is an error in any of the steps
#######################################
function create_user() {
  local default_groups='adm,cdrom,sudo,dip,plugdev'
  local username=$1

  if ! (/usr/sbin/useradd -m -u "${DEFAULT_UID}" "${username}"); then
    return 1
  fi

  if ! (/usr/sbin/usermod -aG "${default_groups}" "${username}"); then
    /usr/sbin/userdel "${username}"
    return 1
  fi

  if ! (/usr/bin/passwd "${username}"); then
    /usr/sbin/userdel "${username}"
    return 1
  fi
}

#######################################
# Main function to initialize the script
#######################################
function main() {

  # Deletes /etc/resolv.conf only if it was not generated by WSL
  if [[ -f /etc/resolv.conf && $(grep -c "WSL" /etc/resolv.conf) == 0 ]]; then
    /bin/rm /etc/resolv.conf
  fi

  # If the default user is already created, we exit the script.
  if getent passwd ${DEFAULT_UID} > /dev/null; then
    return 0
  fi

  dbus-uuidgen --ensure

  echo 'Please create a default Linux user account. The username does not need to match your Windows username.'
  echo 'For more information visit: https://aka.ms/wslusers'

  while true; do
    # Prompt for the username
    local username
    read -rp 'Enter new Linux username: ' username

    create_user "${username}" && break
  done

  if [ "$(grep -c "\[user\]" /etc/wsl.conf)" -eq 0 ]; then
    echo -e "\n[user]\ndefault=${username}">>/etc/wsl.conf
  else
    sed -i "s/\(default=\)\(.*\)/\1${username}/" /etc/wsl.conf
  fi
}

main "$@"
