version: 2.1
parameters:
  package-version:
    type: string
    default: "1.0"

jobs:

  buildtest:
    docker:
      - image: debian:trixie
    resource_class: small      
    environment:
      DEBEMAIL: "contact@whitewaterfoundry.com"
      DEBFULLNAME: "Whitewater Foundry, Ltd. Co."
    steps:
      - checkout
      - run:
          name: Ensure we have devscripts and debuild installed
          command: |
            apt-get -y -q update
            apt-get -y -q install devscripts debhelper
      - run:
          name: Update changelog
          command: |
            rm ./debian/changelog
            dch --create --distribution trixie --package "pengwin-base" --newversion << pipeline.parameters.package-version >>-${CIRCLE_BUILD_NUM} "Built on Circle CI"
      - run:
          name: Build the package
          command: debuild -i -us -uc -b
      - run:
          name: Create workspace
          command: mkdir -p /tmp/pkgs
      - run:
          name: Copy package to workspace
          command: cp ../pengwin-base_<< pipeline.parameters.package-version >>-${CIRCLE_BUILD_NUM}_all.deb /tmp/pkgs
      - persist_to_workspace:
          root: /tmp/pkgs
          paths: [ "." ]
      - store_artifacts:
          name: Store the package as an artifact
          path: /tmp/pkgs
  deploymasterdeb:
    docker:
      - image: cimg/ruby:2.7
    resource_class: small      
    steps:
      - attach_workspace:
          at: /tmp/pkgs
      - run:
          name: Install packageloud cli
          command: gem install package_cloud
      - run:
          name: Push deb package bookworm
          command: package_cloud push whitewaterfoundry/pengwin-base/debian/bookworm /tmp/pkgs/pengwin-base_<< pipeline.parameters.package-version >>-*_all.deb
      - run:
          name: Push deb package trixie
          command: package_cloud push whitewaterfoundry/pengwin-base/debian/trixie /tmp/pkgs/pengwin-base_<< pipeline.parameters.package-version >>-*_all.deb
  deploydevdeb:
    docker:
      - image: cimg/ruby:2.7
    resource_class: small      
    steps:
      - attach_workspace:
          at: /tmp/pkgs
      - run:
          name: Install packageloud cli
          command: gem install package_cloud
      - run:
          name: Push deb package bookworm
          command: package_cloud push whitewaterfoundry/pengwin-base-dev/debian/bookworm /tmp/pkgs/pengwin-base_<< pipeline.parameters.package-version >>-*_all.deb
      - run:
          name: Push deb package trixie
          command: package_cloud push whitewaterfoundry/pengwin-base-dev/debian/trixie /tmp/pkgs/pengwin-base_<< pipeline.parameters.package-version >>-*_all.deb
workflows:
  version: 2
  testdebbuild:
    jobs:
      - buildtest:
          filters:
            branches:
              ignore:
                - development
                - master

  deploymasterbranch:
    jobs:
      - buildtest:
          filters:
            branches:
              only: master
      - deploymasterdeb:
          filters:
            branches:
              only: master
          requires:
            - buildtest
  deploydevbranch:
    jobs:
      - buildtest:
          filters:
            branches:
              only: development
      - deploydevdeb:
          filters:
            branches:
              only: development
          requires:
            - buildtest
