Document: wlinux-base
Title: Debian wlinux-base Manual
Author: <insert document author here>
Abstract: This manual describes what wlinux-base is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wlinux-base/wlinux-base.sgml.gz

Format: postscript
Files: /usr/share/doc/wlinux-base/wlinux-base.ps.gz

Format: text
Files: /usr/share/doc/wlinux-base/wlinux-base.text.gz

Format: HTML
Index: /usr/share/doc/wlinux-base/html/index.html
Files: /usr/share/doc/wlinux-base/html/*.html
