#! /bin/bash

function _winget() {

  local cur=${COMP_WORDS[COMP_CWORD]}
  local prev=${COMP_WORDS[COMP_CWORD - 1]}

  case "$prev" in
  install | show | search)
    local program_list
    program_list="$(winpwsh-exe winget search "${cur}" | sed -z "s/\r/ /g" | tr '[:upper:]' '[:lower:]')"
    mapfile -t COMPREPLY < <(compgen -W "$program_list" "${cur,,}" )
    ;;
  validate | -m | --manifest)
    mapfile -t COMPREPLY < <(compgen -f -X '!*.yml' "${cur}")
    ;;
  *)
    mapfile -t COMPREPLY < <(compgen -W "install show source search hash validate -v --version --info \
                                --help -? -m --manifest" "${cur}")
    ;;
    #   Generate the completion matches and load them into $COMPREPLY array.
  esac

  return 0
}

complete -F _winget winget
